### PR TITLE
161 update video call

### LINKED ISSUE #161: Update video call
Update to the new Ui system

This update should include completion of the feature with ringtone and answer system

### PR DESCRIPTION
**Pull request by codeeMadness**
Hi,

This feature might have some bugs around. But basically, it follows new code styles.

Please help to review. I will try to cover bugs when open other issues.
Feel free to reopen if need me to update some parts.

Regards,

### CODE REVIEW

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness, 
I have reviewed the call feature. It is getting a lot better and closer to a deployable state, but there are still some things that must be fixed before it can be merged to deployment. 

### Here is the list of my observations:

**1. Red dot in browser tab after call ends**
image

<br><br><br><br>
**2. The peer initiating the call does not see himself**
image

<br><br><br><br>
**3. The callers information box options**
image
I think the solution to this one would be to completely remove the information panel on the caller side. As shown in the picture bellow, the message contained in the information box could be used to fill the area where the other peers camera will go.
image

<br><br><br><br>
**4. Button style on the receiving side**
The button on the receiving side works well but the text should be replaced by standard answer and decline buttons since the yes/cancel options are not well adapted for the context but adapted to our style.
image
Here is the standard I mean, you can adapt it to our style as you want.
image

<br><br><br><br>
Thank you

**Review by Liquid-Blocks — CHANGES_REQUESTED** [review]
See comment above

**Comment by codeeMadness** [comment]
Thanks for your feedback. Let me try to cover these issues.

**Comment by Liquid-Blocks** [comment]
I don think this is relevant anymore. Please open a new PR if you wish to include this feature in the Spacetime core sdk.

Thank you.

**Pull request closed without merging**
